services:
  plex:
    image: ghcr.io/scottdkey/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    shm_size: 8g
    environment:
      PLEX_UID: "1000"
      PLEX_GID: "1000"
      LIBVA_DRIVER_NAME: auto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/plex/config:/config
      - /mnt/media:/mnt/media:ro
    tmpfs:
      - /transcode:size=4g,mode=1777
    devices:
      - /dev/dri/renderD128
      - /dev/dri/card0
