//! Plex Media Server plugin. Client + tool surface.
//!
//! Tool surface (one-tool-per-resource):
//!
//! - `plex.{list, detail, create, update, delete}` — endpoint registry CRUD,
//!   generated by `endpoint_resource!` from the toolkit.
//! - `plex.server_info` — server name / version / platform from `/`.
//! - `plex.libraries` — configured library sections from
//!   `/library/sections/all`.
//! - `plex.transcode_health` — **core diagnosis.** Per-session transcode state
//!   from `/status/sessions`, flagging hardware-vs-software (CPU) fallback.
//! - `plex.{install, update, backup, restore}` — full deployment lifecycle,
//!   wrapping the repo's `scripts/` + `lxc/` bootstrap as orca tools.
//!
//! Endpoint resolution: tools accept the endpoint *name* and load
//! `(base_url, token)` from the toolkit-generated `tools::endpoint_db` at call
//! time, mirroring the dockge / jellyfin plugins. Per
//! [[project-colocated-api-clients]] + model B (any creds-holder may execute),
//! the row syncs to every paired peer.
//!
//! ## Typed upstream client
//!
//! `progenitor` generates a typed `plex::api::Client` at build time from the
//! vendored spec (OpenAPI 3.1.1; lowered to 3.0 then pruned to the driven
//! endpoints — see `build.rs`). The generated types do not derive
//! `JsonSchema`, so they never cross an `#[orca_tool]` boundary; the tool
//! surface deserializes upstream JSON into the schema-deriving structs in
//! `diag` and below. The generated module is retained as the typed transport
//! contract.
// Generated progenitor code triggers a raft of pedantic lints; the upstream
// session/transcode payloads are also modeled opaquely where untyped.
#![allow(clippy::disallowed_types)]

pub mod abi_export;
pub mod diag;
pub mod lifecycle;
pub mod tools;

use plugin_toolkit::http::{Client as HttpClient, HttpError, Response};
use plugin_toolkit::thiserror::Error;

use crate::diag::{SessionTranscodeHealth, SessionsEnvelope};

/// Typed upstream client generated by progenitor from the lowered+pruned spec.
#[allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case
)]
pub mod api {
    include!(concat!(env!("OUT_DIR"), "/plex_codegen.rs"));
}

#[derive(Debug, Clone)]
pub struct Config {
    pub base_url: String,
    pub token: String,
}

impl Config {
    pub fn new(base_url: impl Into<String>, token: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            token: token.into(),
        }
    }
}

#[derive(Debug, Error)]
pub enum PlexError {
    #[error(transparent)]
    Http(#[from] HttpError),
    #[error("decode {what}: {source}")]
    Decode {
        what: &'static str,
        #[source]
        source: plugin_toolkit::serde_json::Error,
    },
}

/// Server identity from `/` (the root `MediaContainer`).
#[derive(Debug, Clone, plugin_toolkit::serde::Serialize, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
pub struct ServerInfo {
    pub friendly_name: Option<String>,
    pub version: Option<String>,
    pub platform: Option<String>,
    pub platform_version: Option<String>,
    pub machine_identifier: Option<String>,
}

#[derive(Debug, Clone, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct RootEnvelope {
    #[serde(rename = "MediaContainer", default)]
    media_container: Option<RootContainer>,
}

#[derive(Debug, Clone, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct RootContainer {
    #[serde(rename = "friendlyName", default)]
    friendly_name: Option<String>,
    #[serde(rename = "version", default)]
    version: Option<String>,
    #[serde(rename = "platform", default)]
    platform: Option<String>,
    #[serde(rename = "platformVersion", default)]
    platform_version: Option<String>,
    #[serde(rename = "machineIdentifier", default)]
    machine_identifier: Option<String>,
}

/// One library section from `/library/sections/all`.
#[derive(Debug, Clone, plugin_toolkit::serde::Serialize, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
pub struct LibrarySection {
    pub key: Option<String>,
    pub title: Option<String>,
    pub kind: Option<String>,
    pub locations: Vec<String>,
}

#[derive(Debug, Clone, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct SectionsEnvelope {
    #[serde(rename = "MediaContainer", default)]
    media_container: Option<SectionsContainer>,
}

#[derive(Debug, Clone, Default, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct SectionsContainer {
    #[serde(rename = "Directory", default)]
    directory: Vec<RawSection>,
}

#[derive(Debug, Clone, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct RawSection {
    #[serde(rename = "key", default)]
    key: Option<String>,
    #[serde(rename = "title", default)]
    title: Option<String>,
    #[serde(rename = "type", default)]
    kind: Option<String>,
    #[serde(rename = "Location", default)]
    location: Vec<RawLocation>,
}

#[derive(Debug, Clone, plugin_toolkit::serde::Deserialize)]
#[serde(crate = "plugin_toolkit::serde")]
struct RawLocation {
    #[serde(rename = "path", default)]
    path: Option<String>,
}

/// Hand-written transport. Carries the Plex token on every request as the
/// `X-Plex-Token` header and asks for JSON via `Accept: application/json`.
#[derive(Clone)]
pub struct Client {
    cfg: Config,
    http: HttpClient,
}

impl Client {
    pub fn new(cfg: Config) -> Self {
        Self {
            cfg,
            http: HttpClient::new(),
        }
    }

    pub fn with_http(cfg: Config, http: HttpClient) -> Self {
        Self { cfg, http }
    }

    /// Server name / version / platform.
    pub async fn server_info(&self) -> Result<ServerInfo, PlexError> {
        let resp = self.authed_get("/").await?;
        let env = resp.json::<RootEnvelope>().map_err(PlexError::Http)?;
        let c = env.media_container.unwrap_or(RootContainer {
            friendly_name: None,
            version: None,
            platform: None,
            platform_version: None,
            machine_identifier: None,
        });
        Ok(ServerInfo {
            friendly_name: c.friendly_name,
            version: c.version,
            platform: c.platform,
            platform_version: c.platform_version,
            machine_identifier: c.machine_identifier,
        })
    }

    /// Configured library sections.
    pub async fn libraries(&self) -> Result<Vec<LibrarySection>, PlexError> {
        let resp = self.authed_get("/library/sections/all").await?;
        let env = resp.json::<SectionsEnvelope>().map_err(PlexError::Http)?;
        let sections = env
            .media_container
            .unwrap_or_default()
            .directory
            .into_iter()
            .map(|d| LibrarySection {
                key: d.key,
                title: d.title,
                kind: d.kind,
                locations: d.location.into_iter().filter_map(|l| l.path).collect(),
            })
            .collect();
        Ok(sections)
    }

    /// Active sessions, classified for transcode health.
    pub async fn transcode_health(&self) -> Result<Vec<SessionTranscodeHealth>, PlexError> {
        let resp = self.authed_get("/status/sessions").await?;
        let env = resp.json::<SessionsEnvelope>().map_err(PlexError::Http)?;
        Ok(env
            .media_container
            .metadata
            .into_iter()
            .map(SessionTranscodeHealth::from_raw)
            .collect())
    }

    /// Liveness probe. A bare authed GET of `/identity` that returns the HTTP
    /// status so a caller can distinguish "served fast" from "timed out / 5xx
    /// under memory thrash" — the real-I/O pressure signal observable from
    /// outside the guest. Errors (timeout, connection refused) propagate.
    pub async fn liveness(&self) -> Result<u16, PlexError> {
        Ok(self.authed_get("/identity").await?.status)
    }

    async fn authed_get(&self, path: &str) -> std::result::Result<Response, HttpError> {
        self.http
            .get(self.url(path))
            .header("x-plex-token", &self.cfg.token)
            .header("accept", "application/json")
            .send()
            .await
    }

    fn url(&self, path: &str) -> String {
        format!("{}{}", self.cfg.base_url.trim_end_matches('/'), path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use plugin_toolkit::serde_json;
    use wiremock::matchers::{header, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    #[tokio::test]
    async fn server_info_parses() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/"))
            .and(header("x-plex-token", "tok"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "MediaContainer": {
                    "friendlyName": "media",
                    "version": "1.40.0",
                    "platform": "Linux"
                }
            })))
            .mount(&server)
            .await;
        let info = Client::new(Config::new(server.uri(), "tok"))
            .server_info()
            .await
            .unwrap();
        assert_eq!(info.version.as_deref(), Some("1.40.0"));
        assert_eq!(info.friendly_name.as_deref(), Some("media"));
    }

    #[tokio::test]
    async fn libraries_parses() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/library/sections/all"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "MediaContainer": {
                    "Directory": [
                        { "key": "1", "title": "Movies", "type": "movie",
                          "Location": [{ "path": "/data/movies" }] }
                    ]
                }
            })))
            .mount(&server)
            .await;
        let libs = Client::new(Config::new(server.uri(), "tok"))
            .libraries()
            .await
            .unwrap();
        assert_eq!(libs.len(), 1);
        assert_eq!(libs[0].title.as_deref(), Some("Movies"));
        assert_eq!(libs[0].locations, vec!["/data/movies"]);
    }

    #[tokio::test]
    async fn transcode_health_flags_software_fallback() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/status/sessions"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "MediaContainer": {
                    "size": 2,
                    "Metadata": [
                        { "sessionKey": "1", "title": "Film",
                          "TranscodeSession": { "videoDecision": "transcode",
                                                "transcodeHwFullPipeline": false } },
                        { "sessionKey": "2", "title": "Show",
                          "TranscodeSession": { "videoDecision": "transcode",
                                                "transcodeHwFullPipeline": true } }
                    ]
                }
            })))
            .mount(&server)
            .await;
        let sessions = Client::new(Config::new(server.uri(), "tok"))
            .transcode_health()
            .await
            .unwrap();
        assert_eq!(sessions.len(), 2);
        assert!(sessions[0].software_fallback);
        assert!(!sessions[1].software_fallback);
    }
}
